FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy@sha256:7c808ca379d3836044627a0bb5d4fc84520f41bca775706d37ca6863fea3567b AS build
WORKDIR /src

RUN dotnet dev-certs https \
    && apt-get update \
    && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g @angular/cli

COPY ["AspNetAngularTemplate/AspNetAngularTemplate.csproj", "AspNetAngularTemplate/"]
RUN dotnet restore "AspNetAngularTemplate/AspNetAngularTemplate.csproj"
COPY . .
WORKDIR "/src/AspNetAngularTemplate"
RUN dotnet build "AspNetAngularTemplate.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AspNetAngularTemplate.csproj" -c Release -o /app/publish

FROM publish AS final
WORKDIR /app

EXPOSE 44461 44462

COPY --from=build /root/.dotnet/corefx/cryptography/x509stores/my/* /root/.dotnet/corefx/cryptography/x509stores/my/
COPY --from=publish /app/publish .

ENTRYPOINT bash ./AspNetAngularTemplate/migrate.sh ${ConnectionString}